source 'https://rubygems.org'

# DEFAULT GEMS
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.8'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development
gem 'cloudinary'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

# PROJECT GEMS
gem 'thin'
gem 'carrierwave'
gem 'bootstrap-sass'
  # git: 'https://github.com/twbs/bootstrap-sass', 
  # ref: '540ad23430b1bdb2c72591daf61507ec9e38e468'

#gem 'rmagick', '~> 2.13.2', require: false
# gem 'threejs-rails', git: 'https://github.com/marvindanig/threejs-rails.git'
gem 'markdown-rails'
gem 'd3-rails'
gem 'devise'
#gem 'mysql2', '0.3.16'
gem 'normalize-rails'
gem 'underscore-rails'
# gem 'jquery-sparkline-rails', git: "https://github.com/cubus/jquery-sparkline-rails.git"
gem 'jquery-ui-rails'
gem 'htmlbeautifier'
gem 'chart-js-rails'
gem "haml-rails", "~> 0.9"
gem 'ace-rails-ap'
gem 'omniauth'
gem 'omniauth-google-oauth2'

